### ISSUE TITLE
[BE] Transaksi

### ISSUE THREAD

**Issue by RaidyMR** [Pak-Thani/consumer-api#25]
## Deskripsi
Fitur ini dibutuhkan sehingga client dapat menyimpan riwayat transaksi yang terjadi di aplikasi

## Implementasi Detail

Data transaksi harus dapat disimpan di database sehingga riwayat transaksi dapat diunduh oleh client. 

## Acceptance Criteria

- [x]  Setiap Ada Transaksi, Jumlah stok harus dikurangi sesuai dengan item yang dibeli
- [x]  Ada fitur hapus/tambah stok manual, untuk kejadian human error ( ex : pembatalan item lewat whatsapp ) 
- [x]  Data Field sudah sesuai kriteria

- Nama
- Kabupaten
- Kecamatan
- Alamat
- Alamat Detail : Opsional ( placeholder : mis. rumah warna putih dengan bunga didepannya )
- Nomor Hp/Wa
- Metode Pembayaran (bisa pake radio button) (COD dan Transfer Bank

nambah 
- Bukti Pembayaran

**Comment by RaidyMR** [comment]
Secara umum, User Flow mengikuti https://www.untuckit.com/ dengan alur sbb:

- Alur transaksi terjadi ketika pengguna menekan tombol checkout setelah memilih barang belanjaan.
- Pengguna akan mengisi data alamat serta nomor telepon  pengguna.
- Dilanjutkan dengan memilih metode pembayaran [COD/transfer bank]

**Comment by manokrajin** [comment]
field yang mungkin dimasukkan kedalam desain : 

- Nama
- Kabupaten
- Kecamatan
- Alamat
- Alamat Detail : Opsional ( placeholder : mis. rumah warna putih dengan bunga didepannya )
- Nomor Hp/Wa
- Metode Pembayaran (bisa pake radio button) (COD dan Transfer Bank

**Comment by RaidyMR** [comment]
boleh minta apa aja yang bisa dilakukan dengan transaksi, sama field apa aja yang dibutuhkan? @manokrajin

**Comment by RaidyMR** [comment]
boleh minta contoh input alamat detail? @manokrajin

**Comment by RaidyMR** [comment]
kemudian data nomor wa sama alamat detail itu setelah dikirim dan diterima oleh BE perlu diolah seperti apa?

**Comment by manokrajin** [comment]
contoh alamat detail misalnya : 
Alamat user ada di kebayoran lama, jakarta selatan. detailnya itu adalah kosan hijau yang ada pagar hitam depannya. jadi untuk ngemudahin kurir untuk ngirim barang.

tapi nanti waktu di download sama client (pakthani), nomor whatsapp dan detail alamat gaboleh termasuk di dalam csv nya.
setelah didownload, kalo bisa baris untuk nomor whatsapp dan detail alamat dihapus aja,

ini jatuhnya inisiatif, bukan main goal kita. main goalnya tetep supaya si client bisa ngumpulin data user dan mungkin mau diolah lagi sama mereka. harapannya sih cuman user privacy supaya lebih terjaga

**Comment by RaidyMR** [comment]
Data pribadi tidak boleh disimpan ini maksudnya disimpan dimana? @manokrajin

**Comment by RaidyMR** [comment]
field modelnya apa aja selain yang udah di list dibawah ini? @manokrajin 

> field yang mungkin dimasukkan kedalam desain :
> 
> * Nama
> * Kabupaten
> * Kecamatan
> * Alamat
> * Alamat Detail : Opsional ( placeholder : mis. rumah warna putih dengan bunga didepannya )
> * Nomor Hp/Wa
> * Metode Pembayaran (bisa pake radio button) (COD dan Transfer Bank

**Comment by RaidyMR** [comment]
"riwayat transaksi dapat diunduh oleh client" ini kyakny bukan disini tasknya

**Comment by RaidyMR** [comment]
tolong deskripsikan juga cara BE dapat datanya di deskripsi/implementasi detail @manokrajin
