### ISSUE TITLE
[BE] Whatsapp Message, when user click "Check Status Transaksi"

### ISSUE THREAD

**Issue by manokrajin** [Pak-Thani/consumer-api#27]

**Comment by luthfianum** [comment]
### Whatsapp API (Cloud API)
---
Pre-req :
- Whatsapp Business
- Akun Meta Developer
- Meta App
- Webhook

Pricing : 
- Gratis 1000 Percakapan tiap bulan yg direset tiap bulan sesuai timezone
- Untuk indonesia, biayanya adalah Rp.450.80 untuk tiap percakapan yg diinisiasi oleh Akun Bisnis, Rp. 270.48 untuk tiap percakapan yg diinisiasi oleh pengguna biasa
- Jika ingin diatas limit bulanan, harus menyertakan Credit Card

Features : 
- Mengirimkan Pesan ke orang / orang-orang
- Read Status Update
- send media & download media

FYI : 
- Ada Postman Documentationnya
- Auth pake Access Token

**Comment by luthfianum** [comment]
Update :
- 1 percakapan dianggap 24 jam dari pesan pertama

**Comment by manokrajin** [comment]
Belum nambahin shift pengiriman

**Comment by luthfianum** [comment]
untuk penggunaan akun meta dan aplikasi didalam meta butuh :

- akun Meta Developer (bisa sign-up dari facebook) dari pakthani karena aplikasi bakalan terikat langsung dengan akun
- akun WA bussiness
- domain aplikasi
- halaman Kebijakan Privasi
- ...

@manokrajin

**Comment by luthfianum** [comment]
![Image](https://user-images.githubusercontent.com/66907446/200717142-a68a6da8-816e-4827-b974-4be5e38c4a50.png)

contoh struktur pesan template, ada header, content, CTA (click-to-action) Button

**Comment by luthfianum** [comment]
selanjutnya yg dibutuhkan adalah : 

- [ ] Halaman Privacy Policy ( @Angelloey @Aryanda04 @manokrajin )
- [ ] Akun bisnis yg terverifikasi Meta ( @manokrajin )
- [ ] Template pesan ( @manokrajin )
