### ISSUE TITLE
[BE] Tampilkan Transaksi dari tanggal hingga tanggal

### ISSUE THREAD

**Issue by manokrajin** [Pak-Thani/consumer-api#29]
## Deskripsi

Fitur ini diperlukan client untuk merekap laporan transaksi dari tanggal ke tanggal

## Implementasi Detail

Di dalam djanggo, sudah tersedia laporan untuk harian, mingguan, bulanan. tapi, jika client tidak disiplin dalam melakukan rekap data, maka akan terjadi redundansi pada data yang diunduh, ambil kasus misalnya mau melakukan rekap januari, tapi baru diunduh pada pertengahan februari. maka saat diunduh bulanan, client akan mendapatkan data sampai dengan pertengahan januari, dan tidak mendapatkan data dari awal januari. untuk menutupi kemungkinan ini, maka perlu fitur filter transaksi dari tanggal ke tanggal

## Acceptance Criteria

- [ ] client dapat memasukkan tanggal awal dan tanggal akhir pada filter tanggal
- [ ] client dapat mengunduh transaksi dari tanggal yang ditetapkan

**Comment by RaidyMR** [comment]
seperti biasa, deskripsi task tolong @manokrajin.

**Comment by manokrajin** [comment]
> seperti biasa, deskripsi task tolong @manokrajin.

makasih sudah mengingantkan mas tapid
